name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and deploy
        run: |
          cd ~/dockers/paaws-frontend/PAAWS2
          npm install
          npm run build
          docker compose down           # <- Para evitar conflito com porta 3000
          docker compose build --no-cache
          docker compose up -d
